import { Project, Bug, TestCase, ChecklistItem, HistoryEntry } from "./types";

export const seedProjects: Project[] = [
  {
    id: "proj-1",
    name: "AI Social Creator",
    slug: "ai-social-creator-web",
    url: "https://ai-social-creator-web.vercel.app",
    platform: "web",
    status: "active",
    lastTested: "2026-03-18",
  },
  {
    id: "proj-2",
    name: "AI Social Creator (iOS)",
    slug: "ai-social-creator-ios",
    platform: "ios",
    status: "in-dev",
    lastTested: "2026-03-10",
  },
  {
    id: "proj-3",
    name: "Shield Scan",
    slug: "shield-scan-web",
    url: "https://shieldscan.lxgic.studio",
    platform: "web",
    status: "active",
    lastTested: "2026-03-15",
  },
  {
    id: "proj-4",
    name: "Shield Scan (Mobile)",
    slug: "shield-scan-mobile",
    platform: "ios",
    status: "in-dev",
  },
  {
    id: "proj-5",
    name: "ChefLXGIC",
    slug: "cheflxgic",
    url: "https://apps.apple.com/app/cheflxgic",
    platform: "ios",
    status: "active",
    lastTested: "2026-03-12",
  },
  {
    id: "proj-6",
    name: "Chore Champ",
    slug: "chore-champ",
    platform: "ios",
    status: "active",
    lastTested: "2026-03-16",
  },
  {
    id: "proj-7",
    name: "Whale Factor",
    slug: "whale-factor",
    url: "https://whalefactor.com",
    platform: "web",
    status: "active",
    lastTested: "2026-03-14",
  },
  {
    id: "proj-8",
    name: "Machine Brief",
    slug: "machine-brief",
    url: "https://machinebrief.com",
    platform: "web",
    status: "active",
    lastTested: "2026-03-17",
  },
  {
    id: "proj-9",
    name: "LXGIC Hub",
    slug: "lxgic-hub",
    url: "https://lxgic-hub.vercel.app",
    platform: "web",
    status: "active",
    lastTested: "2026-03-19",
  },
  {
    id: "proj-10",
    name: "LXGIC Studios Site",
    slug: "lxgic-studios-site",
    url: "https://lxgicstudios.com",
    platform: "web",
    status: "maintenance",
    lastTested: "2026-03-13",
  },
  {
    id: "proj-11",
    name: "LXGIC Vault",
    slug: "lxgic-vault",
    url: "https://lxgic-vault.vercel.app",
    platform: "web",
    status: "active",
    lastTested: "2026-03-11",
  },
];

export const seedTestCases: TestCase[] = [
  {
    id: "tc-1",
    projectId: "proj-1",
    name: "Auth Flow - Email Sign Up",
    category: "auth",
    description: "User can sign up with email and password",
    expectedResult: "User account created and redirected to dashboard",
    status: "pass",
    lastRun: "2026-03-18",
  },
  {
    id: "tc-2",
    projectId: "proj-1",
    name: "Google Sign-In",
    category: "auth",
    description: "User can sign in with Google OAuth",
    expectedResult: "Google popup opens, user authenticated, redirected to dashboard",
    status: "pass",
    lastRun: "2026-03-18",
  },
  {
    id: "tc-3",
    projectId: "proj-1",
    name: "Stripe Checkout - Monthly Plan",
    category: "payments",
    description: "User can subscribe to monthly plan via Stripe",
    expectedResult: "Stripe checkout session created, payment processed, subscription active",
    status: "fail",
    lastRun: "2026-03-18",
  },
  {
    id: "tc-4",
    projectId: "proj-1",
    name: "AI Content Generation",
    category: "api",
    description: "User can generate social media content using AI",
    expectedResult: "AI generates content within 10 seconds, content displayed in editor",
    status: "pass",
    lastRun: "2026-03-18",
  },
  {
    id: "tc-5",
    projectId: "proj-1",
    name: "Content Save & Publish",
    category: "ui",
    description: "User can save generated content and schedule for publishing",
    expectedResult: "Content saved to database, appears in scheduled posts list",
    status: "pass",
    lastRun: "2026-03-18",
  },
  {
    id: "tc-6",
    projectId: "proj-1",
    name: "Dashboard Performance",
    category: "performance",
    description: "Dashboard loads within acceptable time",
    expectedResult: "Page loads in under 2 seconds with full content rendered",
    status: "pass",
    lastRun: "2026-03-18",
  },
  {
    id: "tc-7",
    projectId: "proj-1",
    name: "Responsive Layout - Mobile",
    category: "ui",
    description: "All pages render correctly on mobile viewport (375px)",
    expectedResult: "No horizontal scroll, all elements visible and usable",
    status: "skip",
    lastRun: "2026-03-17",
  },
];

export const seedBugs: Bug[] = [
  {
    id: "bug-1",
    projectId: "proj-1",
    title: "Stripe webhook fails on subscription renewal",
    description: "Webhook endpoint returns 500 when Stripe sends invoice.payment_succeeded event for renewal",
    severity: "high",
    status: "open",
    stepsToReproduce: "1. Create a subscription\n2. Wait for renewal event\n3. Check webhook logs",
    assignedTo: "Nathan",
    createdAt: "2026-03-17T10:00:00Z",
    updatedAt: "2026-03-17T10:00:00Z",
  },
  {
    id: "bug-2",
    projectId: "proj-1",
    title: "AI generation timeout on long prompts",
    description: "When user provides a prompt longer than 500 chars, generation times out",
    severity: "medium",
    status: "in-progress",
    assignedTo: "Nathan",
    createdAt: "2026-03-16T14:00:00Z",
    updatedAt: "2026-03-18T09:00:00Z",
  },
  {
    id: "bug-3",
    projectId: "proj-3",
    title: "Scan results not loading for large domains",
    description: "When scanning domains with 100+ pages, results panel shows infinite spinner",
    severity: "high",
    status: "open",
    createdAt: "2026-03-15T08:00:00Z",
    updatedAt: "2026-03-15T08:00:00Z",
  },
  {
    id: "bug-4",
    projectId: "proj-7",
    title: "Chart rendering glitch on Safari",
    description: "Trading charts flicker on Safari 17+ when switching timeframes",
    severity: "medium",
    status: "open",
    createdAt: "2026-03-14T11:00:00Z",
    updatedAt: "2026-03-14T11:00:00Z",
  },
  {
    id: "bug-5",
    projectId: "proj-9",
    title: "Dark mode toggle doesn't persist",
    description: "User preference for dark/light mode resets on page reload",
    severity: "low",
    status: "resolved",
    assignedTo: "Nathan",
    createdAt: "2026-03-10T16:00:00Z",
    updatedAt: "2026-03-19T12:00:00Z",
  },
];

const defaultChecklistLabels = [
  { label: "Responsive Design", category: "UI" },
  { label: "Cross-Browser Testing", category: "UI" },
  { label: "Performance Audit", category: "Performance" },
  { label: "Security Scan", category: "Security" },
  { label: "Accessibility (a11y)", category: "Accessibility" },
  { label: "SEO Meta Tags", category: "SEO" },
  { label: "Error Handling", category: "Reliability" },
  { label: "Loading States", category: "UI" },
  { label: "404 Pages", category: "UI" },
  { label: "Analytics Integration", category: "Analytics" },
];

export function generateChecklistForProject(projectId: string): ChecklistItem[] {
  return defaultChecklistLabels.map((item, idx) => ({
    id: `cl-${projectId}-${idx}`,
    projectId,
    label: item.label,
    checked: false,
    category: item.category,
  }));
}

export const seedHistory: HistoryEntry[] = [
  {
    id: "hist-1",
    projectId: "proj-1",
    type: "test-run",
    description: "Ran 7 test cases — 5 passed, 1 failed, 1 skipped",
    timestamp: "2026-03-18T15:00:00Z",
  },
  {
    id: "hist-2",
    projectId: "proj-1",
    type: "bug-found",
    description: "Found: Stripe webhook fails on subscription renewal",
    timestamp: "2026-03-17T10:00:00Z",
  },
  {
    id: "hist-3",
    projectId: "proj-3",
    type: "bug-found",
    description: "Found: Scan results not loading for large domains",
    timestamp: "2026-03-15T08:00:00Z",
  },
  {
    id: "hist-4",
    projectId: "proj-9",
    type: "bug-resolved",
    description: "Resolved: Dark mode toggle doesn't persist",
    timestamp: "2026-03-19T12:00:00Z",
  },
  {
    id: "hist-5",
    projectId: "proj-1",
    type: "bug-found",
    description: "Found: AI generation timeout on long prompts",
    timestamp: "2026-03-16T14:00:00Z",
  },
];
